language: scala

scala:
  - "2.10.5"

jdk:
  - oraclejdk8

env:
  - CASSANDRA_VERSION=2.1.14 SPARK_VERSION=1.5.2 SPARK_PACKAGE_TYPE=hadoop2.6
  - CASSANDRA_VERSION=2.2.6 SPARK_VERSION=1.5.2 SPARK_PACKAGE_TYPE=hadoop2.6

  - CASSANDRA_VERSION=2.2.6 SPARK_VERSION=1.6.1 SPARK_PACKAGE_TYPE=hadoop2.6
  - CASSANDRA_VERSION=3.0.7 SPARK_VERSION=1.6.1 SPARK_PACKAGE_TYPE=hadoop2.6
  - CASSANDRA_VERSION=3.7   SPARK_VERSION=1.6.1 SPARK_PACKAGE_TYPE=hadoop2.6

addons:
  apt:
    packages:
    - build-essential
    - python-dev
    - python-pip
    - python-virtualenv
    - libev4
    - libev-dev
  
script: JVM_OPTS= make clean dist start-cassandra test-travis stop-cassandra

sudo: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2
    - $HOME/.sbt
    - $HOME/.local
    - $HOME/.cache/pip

